//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RangeObjects {
  
  
  [System.Serializable()]
  public enum RangeTypeID {
    
    LAUNCH_PROJECTILE = 0,
    
    LAUNCH_PROJECTILE_CURSOR = 1,
    
    ATTRACTIVE_OBJECT = 2,
    
    ATTRACTIVE_OBJECT_ACTIVE = 3,
    
    TARGET_ZONE = 4,
    
    SIGHT_VISION = 5,

    NOT_DISPLAYED = 6
  }
}
