//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LevelManagement {
  
  
  [System.Serializable()]
  public enum LevelZonesID {
    NONE = 0,
    TestScene = 1,
    RTP_TEST = 3,
    INFINITE_LEVEL = 4,
    StartMenu = 17,

    ADVENTURE_TEST = 18
  }
}
