//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LevelManagement
{


    [System.Serializable()]
    public enum LevelZoneChunkID
    {
        NONE = 0,
        INFINITE_LEVEL = 3,
        RTP_PUZZLE_CREATION_TEST = 4,
    }
}
