//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LevelManagement {
  
  
  [System.Serializable()]
  public enum LevelAvailabilityTimelineNodeID {
    
    SewersLV1_Unlock = 0,
    
    SewersLV2_Unlock = 1,
    
    _Level1_MainRoad_Unlock = 2,
  }
}
