//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor_MainGameCreationWizard
{
    
    
    public class NameConstants
    {
        
        public static string BaseLevelChunkPrefab = "_BaseLevelPrefab";
        
        public static string LevelCompletionConditionConfigurationName = "_LevelCompletionCondition";
        
        public static string LevelCompletionInherentData = "_LevelCompletionInherentData";
        
        public static string PuzzleLevelDynamics = "_PuzzleLevelDynamics";
        
        public static string AdventureLevelDynamics = "_AdventureLevelDynamics";
        
        public static string LevelHierarchyConfigurationData = "_LevelHierarchyConfigurationData";
        
        public static string LevelSceneConfigurationData = "_LevelZonesSceneConfigurationData";
        
        public static string LevelChunkSceneConfigurationData = "_ChunkZonesSceneConfigurationData";
    }
}
