//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectionWheel {
  
  
  [System.Serializable()]
  public enum SelectionWheelNodeConfigurationId {
    
    GRAB_CONTEXT_ACTION_WHEEL_CONFIG = 0,
    
    GIVE_CONTEXT_ACTION_WHEEL_CONFIG = 1,
    
    TALK_CONTEXT_ACTION_WHEEL_CONFIG = 2,
    
    THROW_PLAYER_PUZZLE_WHEEL_CONFIG = 3,
    
    ATTRACTIVE_OBJECT_LAY_WHEEL_CONFIG = 4,
    
    EDITOR_TEST = 5,
  }
}
