//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualFeedback {
  
  
  [System.Serializable()]
  public enum DottedLineID {
    
    PROJECTILE_POSITIONING = 0,
    
    ATTRACTIVE_OBJECT = 1,
    
    REPELABLE_OBJECT_FEEDBACK = 2,
  }
}
