site_name: ProjectUndefined-Prototype
theme: 'windmill'
nav:
    - 'Range intersection': 'range_intersection.md'
    - 'Animator playable': 'animator_playable.md'
extra_javascript:
    - ./js/custom.js
extra_css:
    - ./css/custom.css