//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum DiscussionTextID
    {

        SWER_RTP_1_DOOR = 0,

        _1_Town_Bouncer_AskID = 1,

        _1_Town_GardenWatchman_Forbidden_NodeEditor_1 = 2,

        _1_Town_GardenWatchman_Forbidden_NodeEditor_2 = 3,

        _1_Town_GardenWatchman_Forbidden_NodeEditor_3 = 4,

        _1_Town_GardenWatchman_Forbidden_NodeEditor_4 = 5,

        _1_Town_GardenWatchman_Forbidden_NodeEditor_5 = 6,

        _1_Town_GardenWatchman_Forbidden_NodeEditor_6 = 7,

        _1_Town_GardenWatchman_Forbidden_NodeEditor_7 = 8,

        _1_Town_Girl_ToParkInfiltration_NodeEditor_1 = 9,

        _1_Town_Girl_ToParkInfiltration_NodeEditor_2 = 10,

        _1_Town_Girl_ToParkInfiltration_NodeEditor_3 = 11,

        _1_Town_Girl_ToParkInfiltration_NodeEditor_4 = 12,

        _1_Town_Girl_ToParkInfiltration_NodeEditor_5 = 13,

        _1_Town_Girl_ToParkInfiltration_NodeEditor_6 = 14,
        
        DummyItemDescription = 15,

        Tutorial_Movement = 16,

        Tutorial_PuzzleTimeElapse = 17,

        Tutorial_PuzzleContextAactionAwake = 18,
        
        _1_Town_Girl_ToParkInfiltration_NodeEditor_7 = 19,

    }
}
