//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Input
{


    [System.Serializable()]
    public enum InputID
    {
        NONE = 0,
        ACTION_DOWN = 1,
        LEFT_DOWN_HOLD = 2,
        RIGHT_DOWN_HOLD = 3,
        UP_DOWN_HOLD = 4,
        DOWN_DOWN_HOLD = 5,
        CANCEL_DOWN = 6,
        CANCEL_DOWN_HOLD = 7,
        INVENTORY_DOWN = 8,
        CAMERA_ROTATION_DOWN_HOLD = 9,
        TIME_FORWARD_DOWN_HOLD = 10,
        PUZZLE_RESET_DOWN_HOLD = 11,
        SWITCH_SELECTION_DOWN = 12,
        CAMERA_ZOOM = 13
    }
}
