//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timelines {
  
  
  [System.Serializable()]
  public enum TimelineID {
    
    LEVEL_AVAILABILITY_TIMELINE = 2,
    
    TESTING_TIMELINE = 99999,
  }
}
